// <auto-generated />
namespace _360Feedback.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class FeedbackDb042715bis : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeedbackDb042715bis));
        
        string IMigrationMetadata.Id
        {
            get { return "201504272006324_FeedbackDb042715bis"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
